<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('59', '/uploads/allimg/150829/1-150R9164942N7.jpg');
$maNum = 1;
$myaddons[$maNum] = array('60', '/uploads/allimg/150829/1-150R91G022314.jpg');
$maNum = 2;
$myaddons[$maNum] = array('61', '/uploads/allimg/150829/1-150R91H055G4.jpg');
$maNum = 3;
$myaddons[$maNum] = array('62', '/uploads/allimg/150829/1-150R91H210333.jpg');
$maNum = 4;
$myaddons[$maNum] = array('63', '/uploads/allimg/150829/1-150R91I63a42.jpg');
$maNum = 5;
$myaddons[$maNum] = array('64', '/uploads/allimg/150829/1-150R91II3F7.jpg');
$maNum = 6;
