<?php
$myaddons = array();
$maNum = 0;
$myaddons[$maNum] = array('65', '/uploads/allimg/150829/1-150R920452c16.png');
$maNum = 1;
$myaddons[$maNum] = array('66', '/uploads/allimg/150829/1-150R92045461H.png');
$maNum = 2;
$myaddons[$maNum] = array('67', '/uploads/allimg/150829/1-150R92059411I.png');
$maNum = 3;
$myaddons[$maNum] = array('68', '/uploads/allimg/150829/1-150R921040VI.jpg');
$maNum = 4;
$myaddons[$maNum] = array('69', '/uploads/allimg/150829/1-150R9211025436.jpg');
$maNum = 5;
$myaddons[$maNum] = array('70', '/uploads/allimg/150829/1-150R921123GG.jpg');
$maNum = 6;
$myaddons[$maNum] = array('71', '/uploads/allimg/150829/1-150R9211450910.png');
$maNum = 7;
