<?php
$z[0]=Array("item","",8,75);
$z[0][4]['name']="单页面管理";
$z[0][4]['link']="templets_one.php";
$z[0][4]['target']="main";
$z[1]=Array("item","",83,179);
$z[1][4]['name']="所有教员档案列表";
$z[1][4]['link']="content_list.php";
$z[1][4]['rank']="a_List,a_AccList";
$z[1][4]['target']="main";
$z[2]=Array("item","",183,292);
$z[2][4]['name']="等审核的教员档案";
$z[2][4]['link']="content_list.php?arcrank=-1";
$z[2][4]['rank']="a_Check,a_AccCheck";
$z[2][4]['target']="main";

?>