<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?>
<!-- Footer -->
<footer class="text-center">
<!-- 
	<div class="footer-above">
		<div class="container">
			<div class="row">
				<div class="footer-col col-md-12">
					<h3>关于我们</h3>
					<p>College家教，简称C家教，专注为您的孩子寻找最合适的教员。我们不仅为您找家教，我们更为您找最适合您孩子的家教</p>
				</div>
				
			</div>
		</div>
	</div> -->
	<div class="footer-below">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<a href="help.php?aid=2">关于我们</a>&nbsp;&nbsp;<a href="help.php?aid=4">联系我们</a><br/>
					Copyright &copy; 2016.凌致教育 All rights reserved.
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll visible-xs visible-sm">
	<a class="btn btn-primary" href="#page-top">
		<i class="fa fa-chevron-up"></i>
	</a>
</div>