<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><footer class="footer " style="text-align:center">
      <!--  <div class="container">
        <div class="row footer-top">
          <div class="col-sm-6 col-lg-6">
            <h4>
              College大学生家教网
            </h4>
            <p>College大学生家教网，最专业的大学生家教网</p>
          </div>
          <div class="col-sm-6  col-lg-5 col-lg-offset-1">
            <div class="row about">
              <div class="col-xs-3">
                <h4>关于</h4>
                <ul class="list-unstyled">
                  <li><a href="/dede/viewArticle.php?aid=2&dopost=view" target="_blank">关于我们</a></li>
                  <li><a href="/dede/viewArticle.php?aid=6&dopost=view" target="_blank">合作建议</a></li>
                </ul>
              </div>
              <div class="col-xs-3">
                <h4>联系方式</h4>
                <ul class="list-unstyled">
                  <li><a href="/dede/viewArticle.php?aid=4&dopost=view" target="_blank">联系我们</a></li>
                </ul>
              </div>
              <div class="col-xs-3">
                <h4>招贤纳士</h4>
                <ul class="list-unstyled">
                  <li><a href="/dede/viewArticle.php?aid=5&dopost=view" target="_blank">招贤纳士</a></li>
                 
                </ul>
              </div>
              <div class="col-xs-3">
                <h4>帮助中心</h4>
                <ul class="list-unstyled">
                  <li><a href="/dede/viewArticle.php?aid=3&dopost=view" target="_blank">帮助中心</a></li>
                  
                </ul>
              </div>
            </div>
    
          </div>
        </div>
        <hr>
        <div class="row footer-bottom">
          <ul class="list-inline text-center">
            <li><a href="" target="_blank">闽ICP备11008151号</a></li><li>闽公网安备11010802014853</li>
          </ul>
        </div>
      </div>-->
      
       <div class="container" style="width:100%;padding:25px 0">
			<div class="row">
				<div class="col-lg-12" style="text-align:center">
					<a href="/help.php?aid=2">关于我们</a>&nbsp;&nbsp;<a href="/help.php?aid=4">联系我们</a><br/>
					Copyright &copy; 2016.凌致教育 All rights reserved.
				</div>
			</div>
	</div>
    </footer>