<?php
$z[0]=Array("include","",0,45);
$z[0][4]['filename']="../home/header.htm";
$z[1]=Array("datalist"," \r\n<div class=\"container\" style=\"margin-top:50px;width:1120px;margin:50px auto\">\r\n	<div class=\"row single-post\">\r\n		<div class=\"col-md-12 col\">\r\n			<div class=\"panel panel-default panel-single-post\">\r\n			 \r\n				<div class=\"panel-heading\" style=\"align:center\">\r\n					<h2 class=\"title mt-0 mb-20\">{dede:field.title/}</h2>\r\n					<div class=\"post-info\">\r\n						<ul class=\"list-inline mb-0\">\r\n							<li>{dede:field.description/}</li>\r\n						</ul>\r\n					</div>\r\n					<!--<div class=\"bg\"></div>  -->\r\n\r\n				</div>\r\n\r\n				<div class=\"panel-body\">\r\n					<p style=\"text-align:center;font-weight:500;\">{dede:field.title/}</p>\r\n                    	<div class=\"entry\">\r\n						{dede:field.body/}					\r\n						</div>\r\n				</div>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n",65,850);
$z[2]=Array("include","",852,898);
$z[2][4]['filename']="../home/footer.html";

?>