<?php
$z[0]=Array("include","",1347,1388);
$z[0][4]['filename']="header_nav.htm";
$z[1]=Array("field","",1517,1536);
$z[1][4]['name']="title";
$z[2]=Array("field","",1554,1579);
$z[2][4]['name']="description";
$z[3]=Array("field","",1747,1765);
$z[3][4]['name']="body";
$z[4]=Array("field","",2124,2143);
$z[4][4]['name']="title";
$z[5]=Array("field","",2212,2230);
$z[5][4]['name']="body";
$z[6]=Array("include","",2300,2337);
$z[6][4]['filename']="footer.htm";

?>