<?php  exit();
/*
Page: /dede/info_list.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>Select mid,city_name From `dede_city` where mid>0</font>
Time2016-05-17 22:43:24
*/
?>
<?php  exit();
/*
Page: /dede/info_list.php
Error: Table 'cjiajiao.dede_from_source' doesn't exist <br />Error sql: <font color='red'>Select mid,source_name From `dede_from_source` where mid>0 </font>
Time2016-05-17 22:43:24
*/
?>
<?php  exit();
/*
Page: /dede/info_list.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member_xueyuan`  WHERE  (bianhao LIKE '%%') LIMIT 0,1;</font>
Time2016-05-17 22:43:24
*/
?>
<?php  exit();
/*
Page: /dede/info_list.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_member_xueyuan`  WHERE  (bianhao LIKE '%%')  ORDER BY mid DESC  LIMIT 0,20</font>
Time2016-05-17 22:43:24
*/
?>
<?php  exit();
/*
Page: /dede/info_add.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>Select mid,city_name From `dede_city` where mid>0</font>
Time2016-05-17 22:43:27
*/
?>
<?php  exit();
/*
Page: /dede/info_add.php
Error: Table 'cjiajiao.dede_from_source' doesn't exist <br />Error sql: <font color='red'>Select mid,source_name From `dede_from_source` where mid>0</font>
Time2016-05-17 22:43:27
*/
?>
<?php  exit();
/*
Page: /dede/info_add.php
Error: Table 'cjiajiao.dede_status' doesn't exist <br />Error sql: <font color='red'>Select mid,status_name From `dede_status` where mid>0</font>
Time2016-05-17 22:43:27
*/
?>
<?php  exit();
/*
Page: /dede/fee_back.php
Error: Table 'cjiajiao.dede_back_fee_record' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_back_fee_record` LIMIT 0,1;</font>
Time2016-05-17 22:43:30
*/
?>
<?php  exit();
/*
Page: /dede/fee_back.php
Error: Table 'cjiajiao.dede_back_fee_record' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_back_fee_record`  ORDER BY apply_time DESC  LIMIT 0,20</font>
Time2016-05-17 22:43:30
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_city` WHERE city_code = '38464' LIMIT 0,1;</font>
Time2016-05-17 22:45:24
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>Select mid,city_name From `dede_city` where mid>0</font>
Time2016-05-17 22:45:24
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member_xueyuan`  WHERE  status LIKE '安排中'  AND  city LIKE '厦门' LIMIT 0,1;</font>
Time2016-05-17 22:45:24
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_member_xueyuan`  WHERE  status LIKE '安排中'  AND  city LIKE '厦门'  ORDER BY createtime DESC  LIMIT 0,20</font>
Time2016-05-17 22:45:24
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_city` WHERE city_code = '38464' LIMIT 0,1;</font>
Time2016-05-17 22:46:10
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_city' doesn't exist <br />Error sql: <font color='red'>Select mid,city_name From `dede_city` where mid>0</font>
Time2016-05-17 22:46:10
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT COUNT(*) AS dd FROM `dede_member_xueyuan`  WHERE  status LIKE '安排中'  AND  city LIKE '厦门' LIMIT 0,1;</font>
Time2016-05-17 22:46:10
*/
?>
<?php  exit();
/*
Page: /info_index.php
Error: Table 'cjiajiao.dede_member_xueyuan' doesn't exist <br />Error sql: <font color='red'>SELECT * FROM `dede_member_xueyuan`  WHERE  status LIKE '安排中'  AND  city LIKE '厦门'  ORDER BY createtime DESC  LIMIT 0,20</font>
Time2016-05-17 22:46:10
*/
?>
